### ISSUE TITLE
Unit tests break downstream package dependencies 

### ISSUE THREAD

**Issue by StephenHodgson** [ultraleap/UnityPlugin#1182]
- unit tests show up in downstream dependencies tests , which causes them to fail. Unit tests should be [explicitly referenced](https://docs.unity3d.com/Manual/cus-tests.html#tests) instead to prevent this.

**Comment by Ultraleap-Dan** [comment]
Thank you for reporting this, this will be added to our engineering backlog to be worked on.

**Comment by Craig-J** [comment]
Can you provide more detail about this? The documentation isn't very clear about explicit referencing. Would turning off "Auto Referenced" be enough to fix the issue?

It seems that tests show up automatically for embedded dependencies (i.e. those directly put into the Packages folder). If you're consuming the package that way there doesn't seem to be a way to disable the tests as far as I can see. I tested turning off "Auto Referenced" with a local package and it doesn't include them in the test runner.

**Comment by StephenHodgson** [comment]
If you'd like I can rework it in a clean branch and submit a new PR

**Comment by StephenHodgson** [comment]
> Would turning off "Auto Referenced" be enough to fix the issue?

I believe you're also missing some explicit references to `nunit.framework.dll` and constraints for `UNITY_INCLUDE_TESTS`

Some of the test fixture attribute declarations are also broken.

**Comment by Craig-J** [comment]
Ah I remember this branch but it seems to never had made it to develop. I'll can see what's needing get it sorted for the next release.

It also mentions about an event in PointerElement - looking at the history it seems that event has never been invoked at any point and it's not obvious what it's meaning is so I'll remove it since breaking changes are allowed in the preview package.

No need to remake another PR I'll handle this from what was on the other PR.

**Comment by StephenHodgson** [comment]
Thanks 🙏

**Comment by Craig-J** [comment]
MR missed the testing cutoff for this sprints release but will be included in the next. We currently aim to release every sprint (2 weeks) and the current one ends today.

**Comment by Craig-J** [comment]
Fixed in 5.8.0 .
