### ISSUE TITLE
Unity MRTK Hand Mesh not detected and usable with Ultraleap Tracking Service Package installed on PC 

### ISSUE THREAD

**Issue by JTflair** [ultraleap/UnityPlugin#1548]
Versions:
Windows: Windows 11
Unity: Unity Hub 3.7.0, Editor Version 2022.3.9f1
OpenXR API Layer 1.6.5

Unity Packages:
- MRTK OpenXR Plugin 1.7.2
- MRTK Toolkit Foundation 2.8.3
- MRTK Toolkit Standard Asset 2.8.3
- AR Foundation 5.0.7
- OpenXR Plugin 1.8.2
- XRCore Utilities 2.2.3
- XR Legacy Input Helper 2.1.10
- XR Plugin Management 4.3.3

I am working on combining Ultraleap Stero IR 170 Tracking Service into my Unity project with HoloLens2, for that I downloaded the Ultraleap Tracking Service Gemini v5.17.3 on Windows to test if it works with the current project. The program works well along either on its control panel and Unity samples so no problem on that. 

All samples and Ultraleap related files are tested on a separate Unity repo that all downloads and configurations are separated with the existing Unity project. It should not have affected the existing Unity project as no changes are made on it.

Hololens2 works well on itself as well, but when I opened my existing Unity project on it through Holographic remoting, my hands are detectable by HoloLens2 (the home window logo could be shown on my wrist) yet no hand meshes or casting rays are created thus I cannot interact (drag or select) with any Hologram.

The problem could not be resolved with any reinstalls of Unity software or versions, MRTK or OpenXR packages, but could only be dealt with when Ultraleap Tracking Software was uninstalled from my PC that everything went back to normal. I also tried ending all tasks related to Ultraleap on the Task manager but it did not help.

I would like to know if there is a way to have the Ultraleap program installed without affecting the existing Unity project. I would still want to test the camera to see what it could do. Thanks for the help.

**Comment by MattGrayUL** [comment]
Hi @JTflair

So the issue seems that you do not want the Ultraleap Tracking Software to interfere with a non-Ultraleap use of your device?

If this is the case, it maybe the the Ultraleap OpenXR layer is stopping your non-Ultraleap hand tracking from being used. you could test this by stopping Ultraleap's OpenXR layer by toggling this option in the Control Panel: 
![image](https://github.com/ultraleap/UnityPlugin/assets/60962475/22985319-10be-48e6-bff4-c233e40cf90c)

This also sounds like a request that is not specific to the Unity Plugin that this Github repository relates to - you may be able to get additional support from our support team via any of the options found here: https://docs.ultraleap.com/useful-links.html

**Comment by JTflair** [comment]
Hi there @MattGrayUL

I tried different combinations of options inside UL control panel, including turning off the OpenXR Support option as you suggested. Unfortunately, it did not help solve the problem. 

I believe ending all running tasks related to UL should have the same output from doing the above, where completing both did not help the situation.

Anyhow, I will get to the support team as you suggested. Thanks for the swift reply anyways.
