### ISSUE TITLE
Allow support for anchoring interaction objects to interaction objects

### ISSUE THREAD

**Issue by Amarcolina** [ultraleap/UnityPlugin#768]
Currently anchoring interaction objects to interaction objects results in the childed objects moving around whenever you move the parent.  For things like panels that you can adjust with buttons on them, this would be an excellent feature to have.

**Comment by nickjbenson** [comment]
To clarify this issue, is this the problem where buttons and slider elements don't stay fixed in local space as the parent moves around, rather, the buttons and sliders sort of bounce around while the parent is moving?

**Comment by nickjbenson** [comment]
@Amarcolina do you remember if "anchoring" means "parenting" here?

If this issue is what I suspected just above, I would say the actionable items for a PR would be:
- [ ] Make sure only position changes are being propagated to Interaction Buttons. This is probably a good first-step at getting inside Interaction Buttons and cleaning them up a bit :)

**Comment by MaxPalmer-UH** [comment]
Looks like the work on this was done. Closing,
