### ISSUE TITLE
An AnchorableBehaviour which is not using AnchorGroups is attachable to any Anchor.

### ISSUE THREAD

**Issue by julienkay** [ultraleap/UnityPlugin#811]
If an AnchorableBehaviour (AB) is not using an AnchorGroup, it can attach to any Anchor in the scene.

If the Anchor property is intended to be used so that ABs only attach to that specific anchor (which I assumed), then the method IsValidAnchor() should check Equality I think:

```
public bool IsValidAnchor(Anchor anchor) {
  if (this.anchorGroup != null) {
    return this.anchorGroup.Contains(anchor);
  }
  else {
    return anchor.Equals(this.anchor);
  }
}
```

The Anchor Tooltip "The current anchor of this AnchorableBehaviour." however makes it sound like thats actually the intended behaviour and the Anchor property only shows whichever Anchor this AB is currently attached to. Based on how you intend the usage, I think the Tooltip should be revised to make that a bit clearer.

**Comment by julienkay** [comment]
Oh, i just saw that the AnchorGroup tooltip clears things up a lot.
In that case, I think it might be good to also grey out the Anchor property, since my first expectation was that I should probably assign something to that property.
But then you couldn't use the "Move Object to Anchor" button anymore, so I don't know which would be the best way to go from here.

**Comment by nickjbenson** [comment]
I agree, the `Anchor` property could clarify the role of AnchorGroups so that this functionality is more clear.

It's useful to have an Anchor attached to an AB's anchor property (1) at edit-time, for the reason you described, and (2) at run-time even if the AB isn't attached, so you can call AttachToAnchor() and send the AB back into its anchor without having to _spawn_ the AB in its anchor.

I also think the use-case where there's only one valid Anchor for an object is probably reasonably common, but the fact that you have to construct a whole single-anchor AnchorGroup and assign it to the AB is a little cumbersome for such a simple constraint. I'll think more about this before I mark this as a to-do. Thoughts @Amarcolina? One option is just adding a toggle switch on the inspector...

**Comment by Amarcolina** [comment]
I haven't really used the Anchorable system, so I couldn't really say D:

**Comment by MaxPalmer-UH** [comment]
Closing here. Tracked as UNITY-745
